GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "content": "Test",
    "important": false
}

###
GET http://localhost:3001/api/notes/65e783963aa56fcd55b73556

###
PUT http://localhost:3001/api/notes/65e8f614511052ca81114c29
Content-type: application/json

{
    "content": "Test update",
    "important": true
}

###
DELETE  http://localhost:3001/api/notes/65e8f614511052ca81114c29

###
POST  http://localhost:3001/api/notes/
Content-type: application/json

{
    "content": "lol",
    "important": false
}